---
kind: pipeline
name: test_pipeline
trigger:
  branch:
    - master
  event:
    - push
    - pull_request

steps:
  - name: "A"
    image: golang:1.21
    settings:
      step: A
    commands:
      - go build

  - name: "B"
    image: golang:1.21
    settings:
      step: B
    commands:
      - go run main.go

---
kind: pipeline
name: extra_pipeline
trigger:
  branch:
    - master
  event:
    - push
    - pull_request

steps:
  - name: "A"
    image: terraform:0.12.26
    settings:
      step: A

  - name: "B"
    image: terraform:0.12.26
    settings:
      step: B